data "amazon-ami" "autogenerated_1" {
  filters = {
    architecture = "x86_64"
    "block-device-mapping.volume-type" = "gp2"
    name = "ubuntu/images/*ubuntu-bionic-18.04-amd64-server-*"
    root-device-type = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners = [
    "099720109477"]
  region = "${var.aws_region}"
}

locals {
  timestamp = regex_replace(timestamp(), "[- TZ:]", "")
}

# template: hcl2_upgrade:4:61: executing "hcl2_upgrade" at <clean_resource_name>: error calling clean_resource_name: unhandled "clean_resource_name" call:
# there is no way to automatically upgrade the "clean_resource_name" call.
# Please manually upgrade to use custom validation rules, `replace(string, substring, replacement)` or `regex_replace(string, substring, replacement)`
# Visit https://packer.io/docs/templates/hcl_templates/variables#custom-validation-rules , https://www.packer.io/docs/templates/hcl_templates/functions/string/replace or https://www.packer.io/docs/templates/hcl_templates/functions/string/regex_replace for more infos.

variable "subnet_id" {
  type = string
  default = ""
}

variable "vpc_id" {
  type = string
  default = ""
}

variable "security_group_ids" {
  type = string
  default = ""
}

variable "aws_region" {
  type = string
  default = ""
}

variable "role_arn" {
  type = string
  default = ""
}

source "amazon-ebs" "ubuntu18-ami" {
  ami_description = "Ubuntu 18.04 AMI configured for polkadot"
  ami_name = "polkadot-ubuntu-{{uuid}}" # missing `clean_resource_name` on isotime # https://github.com/hashicorp/packer/issues/9176
  associate_public_ip_address = true
  instance_type = "t3.small"
  region = var.aws_region

  source_ami_filter {
    filters = {
      architecture                       = "x86_64"
      "block-device-mapping.volume-type" = "gp2"
      name                               = "ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"
      root-device-type                   = "ebs"
      virtualization-type                = "hvm"
    }
    most_recent = true
    owners      = ["099720109477"]
  }

//  source_ami = "{{ data `amazon-ami.autogenerated_1.id` }}"
  ssh_username = "ubuntu"

  vpc_id = var.vpc_id
  subnet_id = var.subnet_id
  security_group_ids = split(",", var.security_group_ids)

  assume_role {
    role_arn = var.role_arn
  }

  tags = {
    Base_AMI_Name = "{{ .SourceAMIName }}"
    Created = "{{isotime}}" # missing `clean_resource_name` # https://github.com/hashicorp/packer/issues/9176
    Distro = "Ubuntu-18.04"
    Id = var.id
    Release = "latest"
  }
}

variable "id" {
  type = string
}

variable "node_exporter_binary_url" {
  type = string
}

variable "node_exporter_password" {
  type = string
}

variable "node_exporter_binary_checksum" {
  type = string
}

variable "instance_count" {
  type = string
}

variable "logging_filter" {
  type = string
}

variable "this_skip_health_check" {
  type = string
}

variable "health_check_enabled" {
  type = string
}

variable "node_exporter_user" {
  type = string
}

variable "project" {
  type = string
}

variable "prometheus_enabled" {
  type = bool
}

variable "consul_enabled" {
  type = bool
}

variable "consul_datacenter" {
  type = string
}

variable "retry_join" {
  type = string
}

variable "consul_gossip_key" {
  type = string
}

variable "consul_auto_encrypt_enabled" {
  type = string
}

variable "consul_connect_enabled" {
  type = string
}

variable "consul_acl_enable" {
  type = string
}

variable "consul_acl_datacenter" {
  type = string
}

variable "consul_acl_token" {
  type = string
}

variable "default_telemetry_enabled" {
  type = string
}

variable "polkadot_binary_url" {
  type = string
}

variable "polkadot_binary_checksum" {
  type = string
}

variable "polkadot_restart_enabled" {
  type = bool
}

variable "telemetry_url" {
  type = string
}

variable "sync_bucket_uri" {
  type = string
}

variable "aws_secret_access_key" {
  type = string
  default = ""
}

variable "aws_access_key_id" {
  type = string
  default = ""
}

variable "module_path" {
  type = string
}

variable "hardening_enabled" {
  type        = bool
  default     = false
}

variable "network_settings" {
  type = string
}

variable "instance_type" {
  type = string
}

variable "deployed_networks" {
  type = string
}

build {
  sources = ["source.amazon-ebs.ubuntu18-ami"]

  provisioner "ansible" {
    extra_arguments = [
      "-e",
      "skip_health_check=${var.this_skip_health_check}",
      "-e",
      "health_check_enabled=${var.health_check_enabled}",
      "-e",
      "region=${var.aws_region}",
      "-e",
      "instance_type=${var.instance_type}",
      "-e",
      "deployed_networks=${var.deployed_networks}",
      "-e",
      "node_exporter_user=${var.node_exporter_user}",
      "-e",
      "node_exporter_password=${var.node_exporter_password}",
      "-e",
      "project=${var.project}",
      "-e",
      "instance_count=${var.instance_count}",
      "-e",
      "node_exporter_binary_url=${var.node_exporter_binary_url}",
      "-e",
      "node_exporter_binary_checksum=${var.node_exporter_binary_checksum}",
      "-e",
      "polkadot_binary_url=${var.polkadot_binary_url}",
      "-e",
      "polkadot_binary_checksum=${var.polkadot_binary_checksum}",
      "-e",
      "polkadot_restart_enabled=${var.polkadot_restart_enabled}",
      "-e",
      "telemetryUrl=${var.telemetry_url}",
      "-e",
      "default_telemetry_enabled=${var.default_telemetry_enabled}",
      "-e",
      "loggingFilter=${var.logging_filter}",
      "-e",
      "consul_enabled=${var.consul_enabled}",
      "-e",
      "consul_datacenter=${var.consul_datacenter}",
      "-e",
      "retry_join_string='${var.retry_join}'",
      "-e",
      "consul_gossip_key='${var.consul_gossip_key}'",
      "-e",
      "consul_auto_encrypt_enabled='${var.consul_auto_encrypt_enabled}'",
      "-e",
      "consul_connect_enabled='${var.consul_connect_enabled}'",
      "-e",
      "consul_acl_enable='${var.consul_acl_enable}'",
      "-e",
      "consul_acl_datacenter='${var.consul_acl_datacenter}'",
      "-e",
      "consul_acl_token='${var.consul_acl_token}'",
      "-e",
      "prometheus_enabled=${var.prometheus_enabled}",
      "-e",
      "network_settings=\"${var.network_settings}\"",
      "-e",
      "aws_access_key_id=${var.aws_access_key_id}",
      "-e",
      "aws_secret_access_key=${var.aws_secret_access_key}",
      "-e",
      "sync_bucket_uri=${var.sync_bucket_uri}",
      "-e",
      "hardening_enabled=${var.hardening_enabled}"
    ]
    playbook_file = "${var.module_path}/ansible/main.yml"
    roles_path = "${var.module_path}/ansible/roles"
  }

  post-processor "manifest" {
    output = "manifest.json"
    strip_path = true
  }
}
